# docker-compose.yml
version: '2'

services:
  graphite:
    image: graphiteapp/graphite-statsd
    ports:
      - "80:80"
      - "2003-2004:2003-2004"
      - "2023-2024:2023-2024"
      - "8125:8125/udp"
      - "8126:8126"
    volumes:
      - "configs/graphite/storage-schemas.conf:/opt/graphite/conf/storage-schemas.conf"
      - "configs/graphite/storage-aggregation.conf:/opt/graphite/conf/storage-aggregation.conf"
    restart: always
  grafana:
    image: grafana/grafana
    ports:
      - "3000:3000"
    environment:
      GF_SECURITY_ADMIN_PASSWORD: secret